### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by saadtazi** [emcniece/tessel-bme280#1]

**Comment by emcniece** [comment]
I'm active, and while I'm not exactly the repo there is a good chance I'll reply :)

**Comment by saadtazi** [comment]
Oops, sorry, I hit enter too quickly...

Hi @emcniece,
do you plan to keep continue working on this repo/npm package?

I plan to port some of the johnny-five mbe-280 functionnalities into its own package (demonstrated [here](https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit/experiment-10-using-the-bme280)). If you don't plan to update this repo, I was wondering if you would be open to transfer the npm ownership of `tessel-bme280` package.

Not a big deal, because I can still publish it under `tessel-bme-280`... Or if you prefer, I can contribute to your repo?

**Comment by emcniece** [comment]
I do plan on updating this repo, but it is indeed a slow process at times. Today was the first day in 5 months that I had time to make a new commit!

I'd rather keep this repo focused on the BME 280. Johnny-Five looks quite comprehensive, but sometimes it's better to pull small pieces as needed.

You're quite welcome to PR to this project!

**Comment by saadtazi** [comment]
I moved ahead and built [this thing](https://github.com/saadtazi/tessel-bme-280#t-273346643) mainly because I wanted to learn tessel, i2c... Note that I am not using `johnnny-five`, i just looked at how that library communicates with tessel. It works for me on the tessel!
 Let me know when you have something that works, i'll test it, compare the results...

FYI: it looks like you are reading one register at a time during `calibrate` (Length = 1), i think it is faster if you read multiple registers at thw same time.
Also: i think you'll have to transpile your code: I think`class` might not work on the tessel
